### ISSUE TITLE
How do i set it up?

### ISSUE THREAD

**Issue by MeetPing** [Lidcer/DiscordYoutubePlayer#1]
The dist and stuff dont exactly work it dosent let me run it 
module.js:549
    throw err;
    ^

Error: Cannot find module '../dist/YoutubePlayer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/craptop-test/Downloads/bot/main.js:3:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by MeetPing** [comment]
and node-opus dosent install.

**Comment by Lidcer** [comment]
have you tried running next commands in a terminal?
```
npm install
npm run build
npm start 
```

**Comment by MeetPing** [comment]
yes
btw its working now i had to install TS replace ../dist/youtubeplayer with ./node_modules/discord-dynamic-music-bot-addon/dist/YoutubePlayer.js

**Comment by MeetPing** [comment]
install ffmpeg

**Comment by MeetPing** [comment]
but setprecense dosent work
it crashed almost instantly

**Comment by MeetPing** [comment]
well the commands dont work either.

**Comment by MeetPing** [comment]
it didnt crash this time but it isnt responding'

**Comment by MeetPing** [comment]
(node:25246) UnhandledPromiseRejectionWarning: ReferenceError: setPresence is not defined
    at Client.client.on (/home/craptop-test/Downloads/bot/main.js:38:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

also something i found.

**Comment by MeetPing** [comment]
also i didnt make a config file i just entereed the information in the file.

**Comment by MeetPing** [comment]
commands arent responding

**Comment by MeetPing** [comment]
@Lidcer

**Comment by Lidcer** [comment]
did you clone the project or did you install it via npm?

**Comment by MeetPing** [comment]
installed via npm but copied the main.js and edited the token api and prefix

**Comment by MeetPing** [comment]
main.js on examples

**Comment by MeetPing** [comment]
this isnt even a bot for me this is for someone.

**Comment by Lidcer** [comment]
main.js(index.js) on example only works if you clone the project. If you install it via npm you have to install discord.js lib first then include the module as require('discord-dynamic-music-bot-addon'). Check README.md file

**Comment by MeetPing** [comment]
is there a example on the one via NPM?
or can you update it?

**Comment by MeetPing** [comment]
Can you just make a example main.js for the npm one?

**Comment by MeetPing** [comment]
How does the one in npm work?

**Comment by Lidcer** [comment]
Sure. I will give me some time.

**Comment by MeetPing** [comment]
the one in npm dosent respond like nothing....

**Comment by MeetPing** [comment]
ugh i just realised its ?player play not ?play
tbh it shouldnt have ?player

**Comment by MeetPing** [comment]
(Yes i changed the prefix to ?)

**Comment by MeetPing** [comment]
._.

**Comment by Lidcer** [comment]
npm version is currently broken. It doesn't work on the newer version of discord. If you want it to work you need to downgrade discord.js to 11.5.1. I am already working on update.
